title: Cardboctober
description: "Each day in October 2016 we made something for Google Cardboard."
# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
