title: Cardboctober
description: "Each day in October we're making something for Google Cardboard. Check back daily to see how we're getting on!"
# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
